### ISSUE TITLE
TypeError: Cannot set property 'available' of undefined

### ISSUE THREAD

**Issue by fortza** [Kondax/node-csgo-floats#5]
```
TypeError: Cannot set property 'available' of undefined
    at GlobalOffensive._availableBots.(anonymous function).on.reason (/xxx/sv/node_modules/csgo-floats/handlers/bot-master.js:60:54)
    at emitOne (events.js:96:13)
    at GlobalOffensive.emit (events.js:188:7)
    at CMClient.<anonymous> (/xxx/sv/node_modules/globaloffensive/index.js:101:9)
    at emitOne (events.js:101:20)
    at CMClient.emit (events.js:188:7)
    at CMClient._disconnected (/xxx/sv/node_modules/steam-client/lib/cm_client.js:294:8)
    at emitOne (events.js:96:13)
    at TCPConnection.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
```

**Comment by Dakshster** [comment]
Can you please help me replicate the error, you're getting?

**Comment by Kondax** [comment]
Closing due to failure to comment on how to replicate the error.
